language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install tox

script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]]; then coveralls; fi
